spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/test
    username: postgres
    password: root
    hikari:
      minimum-idle: 3
      maximum-pool-size: 5

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true

logging:
  level:
    root: INFO
    org.springframework.web: WARN
    com.howtodoinjava: ERROR
    org.hibernate:
      engine.internal: ERROR
      SQL: ERROR
      type.descriptor.sql.BasicBinder: ERROR

server:
  port: 8080